apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-deployment
  labels:
    app: gradio-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-app
  template:
    metadata:
      labels:
        app: gradio-app
    spec:
      containers:
      - name: gradio-container
        image: artmen/gradio-hello-world:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
